/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    posts: Post;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('me' | 'en') | ('me' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
    'work-page': WorkPage;
    'blog-page': BlogPage;
    'contact-page': ContactPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'work-page': WorkPageSelect<false> | WorkPageSelect<true>;
    'blog-page': BlogPageSelect<false> | BlogPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
  };
  locale: 'me' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Opis slike za pristupačnost i SEO (na oba jezika).
   */
  alt?: string | null;
  /**
   * Opcioni izvor / autor fotografije.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * URL dio. Ostavi prazno da se generiše automatski.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Karijerne bjeleške — blog. Svaki tekst postoji na oba jezika.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Kratak opis za karticu i SEO.
   */
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  source?: ('original' | 'ljepota-i-zdravlje') | null;
  /**
   * Link na originalni članak (prikazuje se kao „Pročitaj original").
   */
  sourceUrl?: string | null;
  category?: (number | null) | Category;
  publishedAt?: string | null;
  /**
   * Procjena vremena čitanja (min).
   */
  readingMinutes?: number | null;
  /**
   * URL dio. Ostavi prazno da se generiše automatski.
   */
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  source?: T;
  sourceUrl?: T;
  category?: T;
  publishedAt?: T;
  readingMinutes?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Kontakt podaci, brend i footer — mijenja se bez programera.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName?: string | null;
  brandRole?: string | null;
  email?: string | null;
  /**
   * Prima poruke sa kontakt forme.
   */
  contactRecipient?: string | null;
  instagramHandle?: string | null;
  instagramUrl?: string | null;
  footerBio?: string | null;
  footerCopyright?: string | null;
  footerTagline?: string | null;
  /**
   * Kombinacija fontova (naslovi + tekst).
   */
  fontPairing?: ('fraunces-hanken' | 'playfair-inter' | 'lora-sourcesans' | 'cormorant-worksans') | null;
  /**
   * Glavna tamna teal boja (dugmad, naslovi na svijetloj pozadini).
   */
  colorTealDeep?: string | null;
  /**
   * Sekundarna teal boja (sekcije, akcenti).
   */
  colorTeal?: string | null;
  /**
   * Pozadina (topli papir).
   */
  colorPaper?: string | null;
  /**
   * Boja teksta.
   */
  colorInk?: string | null;
  /**
   * Akcent na tamnoj pozadini (npr. linkovi u footeru).
   */
  colorMint?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  heroEyebrow?: string | null;
  /**
   * Naglasak: _kurziv_ za naglašenu riječ, **podebljano** za jaku riječ.
   */
  heroHeadline?: string | null;
  heroSub?: string | null;
  heroBadge?: string | null;
  /**
   * Portret u hero sekciji.
   */
  heroPortrait?: (number | null) | Media;
  empathyEyebrow?: string | null;
  /**
   * Naglasak: _kurziv_ za naglašenu riječ, **podebljano** za jaku riječ.
   */
  empathyHeadline?: string | null;
  empathyItems?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  storyEyebrow?: string | null;
  /**
   * Naglasak: _kurziv_ za naglašenu riječ, **podebljano** za jaku riječ.
   */
  storyLine?: string | null;
  storyLinkLabel?: string | null;
  storyImage?: (number | null) | Media;
  workEyebrow?: string | null;
  /**
   * Naglasak: _kurziv_ za naglašenu riječ, **podebljano** za jaku riječ.
   */
  workHeadline?: string | null;
  workCards?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  workLinkLabel?: string | null;
  blogEyebrow?: string | null;
  /**
   * Naglasak: _kurziv_ za naglašenu riječ, **podebljano** za jaku riječ.
   */
  blogHeadline?: string | null;
  /**
   * Naglasak: _kurziv_ za naglašenu riječ, **podebljano** za jaku riječ.
   */
  ctaHeadline?: string | null;
  ctaSub?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  eyebrow?: string | null;
  /**
   * Naglasak: _kurziv_ za naglašenu riječ, **podebljano** za jaku riječ.
   */
  headline?: string | null;
  portrait?: (number | null) | Media;
  body?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  quote?: string | null;
  /**
   * Naglasak: _kurziv_ za naglašenu riječ, **podebljano** za jaku riječ.
   */
  ctaHeadline?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-page".
 */
export interface WorkPage {
  id: number;
  eyebrow?: string | null;
  /**
   * Naglasak: _kurziv_ za naglašenu riječ, **podebljano** za jaku riječ.
   */
  headline?: string | null;
  sub?: string | null;
  forWhomHeading?: string | null;
  forWhomText?: string | null;
  /**
   * Naglasak: _kurziv_ za naglašenu riječ, **podebljano** za jaku riječ.
   */
  journeyHeading?: string | null;
  journeySteps?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  journeyQuote?: string | null;
  /**
   * Naglasak: _kurziv_ za naglašenu riječ, **podebljano** za jaku riječ.
   */
  priceHeading?: string | null;
  priceText?: string | null;
  faqHeading?: string | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Uključi sekciju sa preporukama (kasnije, bez redizajna).
   */
  showTestimonials?: boolean | null;
  /**
   * Naglasak: _kurziv_ za naglašenu riječ, **podebljano** za jaku riječ.
   */
  ctaHeadline?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: number;
  eyebrow?: string | null;
  /**
   * Naglasak: _kurziv_ za naglašenu riječ, **podebljano** za jaku riječ.
   */
  headline?: string | null;
  sub?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  eyebrow?: string | null;
  /**
   * Naglasak: _kurziv_ za naglašenu riječ, **podebljano** za jaku riječ.
   */
  headline?: string | null;
  sub?: string | null;
  directHeading?: string | null;
  directText?: string | null;
  formHeading?: string | null;
  formNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  brandRole?: T;
  email?: T;
  contactRecipient?: T;
  instagramHandle?: T;
  instagramUrl?: T;
  footerBio?: T;
  footerCopyright?: T;
  footerTagline?: T;
  fontPairing?: T;
  colorTealDeep?: T;
  colorTeal?: T;
  colorPaper?: T;
  colorInk?: T;
  colorMint?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroHeadline?: T;
  heroSub?: T;
  heroBadge?: T;
  heroPortrait?: T;
  empathyEyebrow?: T;
  empathyHeadline?: T;
  empathyItems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  storyEyebrow?: T;
  storyLine?: T;
  storyLinkLabel?: T;
  storyImage?: T;
  workEyebrow?: T;
  workHeadline?: T;
  workCards?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  workLinkLabel?: T;
  blogEyebrow?: T;
  blogHeadline?: T;
  ctaHeadline?: T;
  ctaSub?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  portrait?: T;
  body?:
    | T
    | {
        text?: T;
        id?: T;
      };
  quote?: T;
  ctaHeadline?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-page_select".
 */
export interface WorkPageSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  sub?: T;
  forWhomHeading?: T;
  forWhomText?: T;
  journeyHeading?: T;
  journeySteps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  journeyQuote?: T;
  priceHeading?: T;
  priceText?: T;
  faqHeading?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  showTestimonials?: T;
  ctaHeadline?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  sub?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  sub?: T;
  directHeading?: T;
  directText?: T;
  formHeading?: T;
  formNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}